-- MySQL Script generated by MySQL Workbench
-- Tue Apr 11 11:40:13 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hb_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hb_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hb_db` DEFAULT CHARACTER SET utf8 ;
USE `hb_db` ;

-- -----------------------------------------------------
-- Table `hb_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hb_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(95) NULL,
  `last_name` VARCHAR(95) NULL,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hb_db`.`habits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hb_db`.`habits` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_holder_id` INT NOT NULL,
  `habit_name` VARCHAR(255) NULL,
  `amount` FLOAT UNSIGNED NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`, `users_holder_id`),
  INDEX `fk_habits_users1_idx` (`users_holder_id` ASC),
  CONSTRAINT `fk_habits_users1`
    FOREIGN KEY (`users_holder_id`)
    REFERENCES `hb_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hb_db`.`helpers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hb_db`.`helpers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_helper_id` INT NOT NULL,
  `habits_id` INT NOT NULL,
  `habits_users_holder_id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`, `users_helper_id`, `habits_id`, `habits_users_holder_id`),
  INDEX `fk_helpers_users_idx` (`users_helper_id` ASC),
  INDEX `fk_helpers_habits1_idx` (`habits_id` ASC, `habits_users_holder_id` ASC),
  CONSTRAINT `fk_helpers_users`
    FOREIGN KEY (`users_helper_id`)
    REFERENCES `hb_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_helpers_habits1`
    FOREIGN KEY (`habits_id` , `habits_users_holder_id`)
    REFERENCES `hb_db`.`habits` (`id` , `users_holder_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hb_db`.`violations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hb_db`.`violations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_helper_id` INT NOT NULL,
  `habits_id` INT NOT NULL,
  `habits_users_holder_id` INT NOT NULL,
  `paid` TINYINT NULL DEFAULT 0,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`, `users_helper_id`, `habits_id`, `habits_users_holder_id`),
  INDEX `fk_violations_users1_idx` (`users_helper_id` ASC),
  INDEX `fk_violations_habits1_idx` (`habits_id` ASC, `habits_users_holder_id` ASC),
  CONSTRAINT `fk_violations_users1`
    FOREIGN KEY (`users_helper_id`)
    REFERENCES `hb_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_violations_habits1`
    FOREIGN KEY (`habits_id` , `habits_users_holder_id`)
    REFERENCES `hb_db`.`habits` (`id` , `users_holder_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
